import = [
	# "~/dotfiles/alacritty/themes/themes/argonaut.toml"

	# "~/dotfiles/alacritty/themes/themes/kanagawa_wave.toml"
	"~/dotfiles/alacritty/themes/themes/oceanic_next.toml"
]


[shell]
program = "/bin/fish"

[env]
term = "alaritty-direct"

[font]
normal = {family = "SauceCodePro Nerd Font Propo", style = "Regular"} 
