import = [
	"~/dotfiles/alacritty/themes/themes/gruvbox-dark.toml"
]


[shell]
program = "/bin/fish"

[env]
term = "xterm-256color"

[font]
normal = {family = "SauceCodePro Nerd Font Propo", style = "Regular"} 
